In [61]:
import pandas as pd
import numpy as np

In [2]:
df1=pd.read_excel("case_study1.xlsx")
df2=pd.read_excel("case_study2.xlsx")

In [3]:
df1.shape

(51336, 26)

In [4]:
df2.shape

(51336, 62)

In [5]:
df1.head()

PROSPECTID  Total_TL  Tot_Closed_TL  Tot_Active_TL  Total_TL_opened_L6M  \
0           1         5              4              1                    0   
1           2         1              0              1                    0   
2           3         8              0              8                    1   
3           4         1              0              1                    1   
4           5         3              2              1                    0   

   Tot_TL_closed_L6M  pct_tl_open_L6M  pct_tl_closed_L6M  pct_active_tl  \
0                  0            0.000                0.0          0.200   
1                  0            0.000                0.0          1.000   
2                  0            0.125                0.0          1.000   
3                  0            1.000                0.0          1.000   
4                  0            0.000                0.0          0.333   

   pct_closed_tl  ...  CC_TL  Consumer_TL  Gold_TL  Home_TL  PL_TL  \
0          0.800  ...      0            0        1        0      4   
1          0.000  ...      0            1        0        0      0   
2          0.000  ...      0            6        1        0      0   
3          0.000  ...      0            0        0        0      0   
4          0.667  ...      0            0        0        0      0   

   Secured_TL  Unsecured_TL  Other_TL  Age_Oldest_TL  Age_Newest_TL  
0           1             4         0             72             18  
1           0             1         0              7              7  
2           2             6         0             47              2  
3           0             1         1              5              5  
4           3             0         2            131             32  

[5 rows x 26 columns]

In [6]:
df2.head()

PROSPECTID  time_since_recent_payment  time_since_first_deliquency  \
0           1                        549                           35   
1           2                         47                       -99999   
2           3                        302                           11   
3           4                     -99999                       -99999   
4           5                        583                       -99999   

   time_since_recent_deliquency  num_times_delinquent  max_delinquency_level  \
0                            15                    11                     29   
1                        -99999                     0                 -99999   
2                             3                     9                     25   
3                        -99999                     0                 -99999   
4                        -99999                     0                 -99999   

   max_recent_level_of_deliq  num_deliq_6mts  num_deliq_12mts  \
0                         29               0                0   
1                          0               0                0   
2                         25               1                9   
3                          0               0                0   
4                          0               0                0   

   num_deliq_6_12mts  ...  pct_CC_enq_L6m_of_L12m  pct_PL_enq_L6m_of_ever  \
0                  0  ...                     0.0                     0.0   
1                  0  ...                     0.0                     0.0   
2                  8  ...                     0.0                     0.0   
3                  0  ...                     0.0                     0.0   
4                  0  ...                     0.0                     0.0   

   pct_CC_enq_L6m_of_ever  max_unsec_exposure_inPct  HL_Flag  GL_Flag  \
0                     0.0                    13.333        1        0   
1                     0.0                     0.860        0        0   
2                     0.0                  5741.667        1        0   
3                     0.0                     9.900        0        0   
4                     0.0                -99999.000        0        0   

   last_prod_enq2  first_prod_enq2  Credit_Score  Approved_Flag  
0              PL               PL           696             P2  
1    ConsumerLoan     ConsumerLoan           685             P2  
2    ConsumerLoan           others           693             P2  
3          others           others           673             P2  
4              AL               AL           753             P1  

[5 rows x 62 columns]

In [7]:
df1=df1[df1["Age_Oldest_TL"]!=-99999]

In [8]:
df2.columns

Index(['PROSPECTID', 'time_since_recent_payment',
       'time_since_first_deliquency', 'time_since_recent_deliquency',
       'num_times_delinquent', 'max_delinquency_level',
       'max_recent_level_of_deliq', 'num_deliq_6mts', 'num_deliq_12mts',
       'num_deliq_6_12mts', 'max_deliq_6mts', 'max_deliq_12mts',
       'num_times_30p_dpd', 'num_times_60p_dpd', 'num_std', 'num_std_6mts',
       'num_std_12mts', 'num_sub', 'num_sub_6mts', 'num_sub_12mts', 'num_dbt',
       'num_dbt_6mts', 'num_dbt_12mts', 'num_lss', 'num_lss_6mts',
       'num_lss_12mts', 'recent_level_of_deliq', 'tot_enq', 'CC_enq',
       'CC_enq_L6m', 'CC_enq_L12m', 'PL_enq', 'PL_enq_L6m', 'PL_enq_L12m',
       'time_since_recent_enq', 'enq_L12m', 'enq_L6m', 'enq_L3m',
       'MARITALSTATUS', 'EDUCATION', 'AGE', 'GENDER', 'NETMONTHLYINCOME',
       'Time_With_Curr_Empr', 'pct_of_active_TLs_ever',
       'pct_opened_TLs_L6m_of_L12m', 'pct_currentBal_all_TL', 'CC_utilization',
       'CC_Flag', 'PL_utilization', 'PL_Fla

In [9]:
remove_columns=[]

for col in df2.columns:
    if df2[df2[col]==-99999].shape[0]>10000:
        remove_columns.append(col)
    

In [10]:
remove_columns

['time_since_first_deliquency',
 'time_since_recent_deliquency',
 'max_delinquency_level',
 'max_deliq_6mts',
 'max_deliq_12mts',
 'CC_utilization',
 'PL_utilization',
 'max_unsec_exposure_inPct']

In [11]:
df2.drop(columns=remove_columns,axis=1,inplace=True)

In [12]:
df2.shape

(51336, 54)

In [13]:
for col in df2.columns:
    df2=df2[df2[col]!=-99999]

In [14]:
df2.shape

(42066, 54)

In [15]:
for i in df1.columns:
    if i in df2.columns:
        print(i)

PROSPECTID


In [62]:
df=pd.merge(df1,df2,how="inner",left_on=["PROSPECTID"],right_on=["PROSPECTID"])

In [63]:
df.shape

(42064, 79)

In [64]:
df.head()

PROSPECTID  Total_TL  Tot_Closed_TL  Tot_Active_TL  Total_TL_opened_L6M  \
0           1         5              4              1                    0   
1           2         1              0              1                    0   
2           3         8              0              8                    1   
3           5         3              2              1                    0   
4           6         6              5              1                    0   

   Tot_TL_closed_L6M  pct_tl_open_L6M  pct_tl_closed_L6M  pct_active_tl  \
0                  0            0.000                0.0          0.200   
1                  0            0.000                0.0          1.000   
2                  0            0.125                0.0          1.000   
3                  0            0.000                0.0          0.333   
4                  0            0.000                0.0          0.167   

   pct_closed_tl  ...  pct_PL_enq_L6m_of_L12m  pct_CC_enq_L6m_of_L12m  \
0          0.800  ...                     0.0                     0.0   
1          0.000  ...                     0.0                     0.0   
2          0.000  ...                     0.0                     0.0   
3          0.667  ...                     0.0                     0.0   
4          0.833  ...                     1.0                     0.0   

   pct_PL_enq_L6m_of_ever  pct_CC_enq_L6m_of_ever  HL_Flag  GL_Flag  \
0                   0.000                     0.0        1        0   
1                   0.000                     0.0        0        0   
2                   0.000                     0.0        1        0   
3                   0.000                     0.0        0        0   
4                   0.429                     0.0        1        0   

   last_prod_enq2  first_prod_enq2  Credit_Score  Approved_Flag  
0              PL               PL           696             P2  
1    ConsumerLoan     ConsumerLoan           685             P2  
2    ConsumerLoan           others           693             P2  
3              AL               AL           753             P1  
4    ConsumerLoan               PL           668             P3  

[5 rows x 79 columns]

In [65]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 42064 entries, 0 to 42063
Data columns (total 79 columns):
 #   Column                      Non-Null Count  Dtype  
---  ------                      --------------  -----  
 0   PROSPECTID                  42064 non-null  int64  
 1   Total_TL                    42064 non-null  int64  
 2   Tot_Closed_TL               42064 non-null  int64  
 3   Tot_Active_TL               42064 non-null  int64  
 4   Total_TL_opened_L6M         42064 non-null  int64  
 5   Tot_TL_closed_L6M           42064 non-null  int64  
 6   pct_tl_open_L6M             42064 non-null  float64
 7   pct_tl_closed_L6M           42064 non-null  float64
 8   pct_active_tl               42064 non-null  float64
 9   pct_closed_tl               42064 non-null  float64
 10  Total_TL_opened_L12M        42064 non-null  int64  
 11  Tot_TL_closed_L12M          42064 non-null  int64  
 12  pct_tl_open_L12M            42064 non-null  float64
 13  pct_tl_closed_L12M          420

In [66]:
cat_col=[]
num_col=[]
for col in df.columns:
    if df[col].dtype=="object":
        cat_col.append(col)
    else:
        num_col.append(col)
        
        
        

In [67]:
cat_col

['MARITALSTATUS',
 'EDUCATION',
 'GENDER',
 'last_prod_enq2',
 'first_prod_enq2',
 'Approved_Flag']

In [68]:
num_col

['PROSPECTID',
 'Total_TL',
 'Tot_Closed_TL',
 'Tot_Active_TL',
 'Total_TL_opened_L6M',
 'Tot_TL_closed_L6M',
 'pct_tl_open_L6M',
 'pct_tl_closed_L6M',
 'pct_active_tl',
 'pct_closed_tl',
 'Total_TL_opened_L12M',
 'Tot_TL_closed_L12M',
 'pct_tl_open_L12M',
 'pct_tl_closed_L12M',
 'Tot_Missed_Pmnt',
 'Auto_TL',
 'CC_TL',
 'Consumer_TL',
 'Gold_TL',
 'Home_TL',
 'PL_TL',
 'Secured_TL',
 'Unsecured_TL',
 'Other_TL',
 'Age_Oldest_TL',
 'Age_Newest_TL',
 'time_since_recent_payment',
 'num_times_delinquent',
 'max_recent_level_of_deliq',
 'num_deliq_6mts',
 'num_deliq_12mts',
 'num_deliq_6_12mts',
 'num_times_30p_dpd',
 'num_times_60p_dpd',
 'num_std',
 'num_std_6mts',
 'num_std_12mts',
 'num_sub',
 'num_sub_6mts',
 'num_sub_12mts',
 'num_dbt',
 'num_dbt_6mts',
 'num_dbt_12mts',
 'num_lss',
 'num_lss_6mts',
 'num_lss_12mts',
 'recent_level_of_deliq',
 'tot_enq',
 'CC_enq',
 'CC_enq_L6m',
 'CC_enq_L12m',
 'PL_enq',
 'PL_enq_L6m',
 'PL_enq_L12m',
 'time_since_recent_enq',
 'enq_L12m',
 'enq_L6

In [69]:
df["MARITALSTATUS"].value_counts()

Married    30886
Single     11178
Name: MARITALSTATUS, dtype: int64

In [70]:
from scipy.stats import chi2_contingency
from statsmodels.stats.outliers_influence import variance_inflation_factor

In [71]:
 for col in cat_col:
        chi2,pval,_,_=chi2_contingency(pd.crosstab(df[col],df["Approved_Flag"]))
        print(col, "---",pval)

MARITALSTATUS --- 3.578180861038862e-233
EDUCATION --- 2.6942265249737532e-30
GENDER --- 1.907936100186563e-05
last_prod_enq2 --- 0.0
first_prod_enq2 --- 7.84997610555419e-287
Approved_Flag --- 0.0


SINCE ALL THE P-VALUE IS LESS THAN 0.05 THEN WE ACCEPTEED ALL FEATURES

In [72]:
vif_data=df[num_col]
total_col=vif_data.shape[1]
column_to_be_kept=[]
column_index=0

In [73]:
for i in range(0,total_col):
    vif_value=variance_inflation_factor(vif_data,column_index)
    print(column_index,"---",vif_value)
    
    if vif_value<=6:
        column_to_be_kept.append(num_col[i])
        column_index+=1
        
    else:
        vif_data=vif_data.drop([num_col[i]],axis=1)
    

0 --- 1.0014714453751745


C:\Users\Dell\anaconda3\Lib\site-packages\statsmodels\stats\outliers_influence.py:198: RuntimeWarning: divide by zero encountered in scalar divide
  vif = 1. / (1. - r_squared_i)


1 --- inf


C:\Users\Dell\anaconda3\Lib\site-packages\statsmodels\stats\outliers_influence.py:198: RuntimeWarning: divide by zero encountered in scalar divide
  vif = 1. / (1. - r_squared_i)


1 --- inf
1 --- 11.320645246142803
1 --- 8.364064272336133
1 --- 6.520792569522153
1 --- 5.149806055710772
2 --- 2.6112073771674944


C:\Users\Dell\anaconda3\Lib\site-packages\statsmodels\stats\outliers_influence.py:198: RuntimeWarning: divide by zero encountered in scalar divide
  vif = 1. / (1. - r_squared_i)


3 --- inf
3 --- 1789.5578922792413
3 --- 8.601096683974646
3 --- 3.832851362174614
4 --- 6.099768198336674
4 --- 5.5814467511930905
5 --- 1.9856551389669772


C:\Users\Dell\anaconda3\Lib\site-packages\statsmodels\stats\outliers_influence.py:198: RuntimeWarning: divide by zero encountered in scalar divide
  vif = 1. / (1. - r_squared_i)


6 --- inf
6 --- 4.809807520859606
7 --- 23.27288184101288
7 --- 30.596519319624697
7 --- 4.384812209111584
8 --- 3.06467356246316
9 --- 2.8986527303140033
10 --- 4.377945210179218
11 --- 2.2078562659546592
12 --- 4.9200182258988345
13 --- 5.215354852494451
14 --- 3.3862072703025055
15 --- 7.841101396160445
15 --- 5.255263829126264


C:\Users\Dell\anaconda3\Lib\site-packages\statsmodels\stats\outliers_influence.py:198: RuntimeWarning: divide by zero encountered in scalar divide
  vif = 1. / (1. - r_squared_i)


16 --- inf
16 --- 7.380644570758274
16 --- 1.4210119761829274
17 --- 8.083354471350239
17 --- 1.6241477619270308
18 --- 7.257891375429919
18 --- 15.596252041665208
18 --- 1.8261329696765474
19 --- 1.5080847785865654
20 --- 2.172126715951356
21 --- 2.623469861333445
22 --- 2.296005407405737
23 --- 7.36062257827916
23 --- 2.1602388310452927
24 --- 2.8686338012754247
25 --- 6.458304472622984
25 --- 2.847480877355157
26 --- 4.753230129394101
27 --- 16.22761360099179
27 --- 6.424833892811067
27 --- 8.887156094086976
27 --- 2.38051089833245
28 --- 8.609683496623786
28 --- 13.067631026848238
28 --- 3.500117421477055
29 --- 1.909120174743784
30 --- 17.007386818210737
30 --- 10.730705629466753
30 --- 2.3558875075565604
31 --- 22.10495526579042
31 --- 2.797253587418863
32 --- 3.4241803843132606
33 --- 10.175437630379681
33 --- 6.40944024648136
33 --- 1.001162721405917
34 --- 3.069223764845478
35 --- 2.8091270098505103
36 --- 20.250688538227966
36 --- 15.864583114854529
36 --- 1.8332179956453991


In [74]:
len(column_to_be_kept)

40

ANOVA

In [75]:
from scipy.stats import f_oneway

In [76]:
columns_to_be_kept_numerical=[]

for i in column_to_be_kept:
    a=list(df[i])
    b=list(df["Approved_Flag"])
    
    group_p1=[value for value,group in zip(a,b) if group =="P1"]
    group_p2=[value for value,group in zip(a,b) if group =="P2"]
    group_p3=[value for value,group in zip(a,b) if group =="P3"]
    group_p4=[value for value,group in zip(a,b) if group =="P4"]
    
    f_statistics,p_value=f_oneway(group_p1,group_p2,group_p3,group_p4)
    
    if p_value<=0.05:
        columns_to_be_kept_numerical.append(i)
        

In [77]:
len(columns_to_be_kept_numerical)

38

In [78]:
cat_col

['MARITALSTATUS',
 'EDUCATION',
 'GENDER',
 'last_prod_enq2',
 'first_prod_enq2',
 'Approved_Flag']

In [79]:
features = columns_to_be_kept_numerical + ['MARITALSTATUS', 'EDUCATION', 'GENDER', 'last_prod_enq2', 'first_prod_enq2']
df = df[features + ['Approved_Flag']]
df.shape

(42064, 44)

In [80]:
df.drop("PROSPECTID",axis=1,inplace=True)

In [81]:
print(df["MARITALSTATUS"].unique())
print(df["EDUCATION"].unique())
print(df["GENDER"].unique())
print(df["last_prod_enq2"].unique())
print(df["first_prod_enq2"].unique())


['Married' 'Single']
['12TH' 'GRADUATE' 'SSC' 'POST-GRADUATE' 'UNDER GRADUATE' 'OTHERS'
 'PROFESSIONAL']
['M' 'F']
['PL' 'ConsumerLoan' 'AL' 'CC' 'others' 'HL']
['PL' 'ConsumerLoan' 'others' 'AL' 'HL' 'CC']


In [36]:
# df.loc[df["EDUCATION"]=="SSC",["EDUCATION"]]=1
# df.loc[df["EDUCATION"]=="OTHERS",["EDUCATION"]]=1
# df.loc[df["EDUCATION"]=="12TH",["EDUCATION"]]=2
# df.loc[df["EDUCATION"]=="GRADUATE",["EDUCATION"]]=3
# df.loc[df["EDUCATION"]=="PROFESSIONAL",["EDUCATION"]]=3
# df.loc[df["EDUCATION"]=="UNDER GRADUATE",["EDUCATION"]]=3
# df.loc[df["EDUCATION"]=="POST-GRADUATE",["EDUCATION"]]=4


In [82]:
df["EDUCATION"]=df["EDUCATION"].replace("OTHERS","SSC")
df["EDUCATION"]=df["EDUCATION"].replace("PROFESSIONAL","GRADUATE")
df["EDUCATION"]=df["EDUCATION"].replace("UNDER GRADUATE","GRADUATE")


In [83]:
df["EDUCATION"].unique()

array(['12TH', 'GRADUATE', 'SSC', 'POST-GRADUATE'], dtype=object)

In [84]:
df.shape

(42064, 43)

In [85]:
df.columns

Index(['pct_tl_open_L6M', 'pct_tl_closed_L6M', 'Tot_TL_closed_L12M',
       'pct_tl_closed_L12M', 'Tot_Missed_Pmnt', 'CC_TL', 'Home_TL', 'PL_TL',
       'Secured_TL', 'Unsecured_TL', 'Other_TL', 'Age_Oldest_TL',
       'Age_Newest_TL', 'time_since_recent_payment',
       'max_recent_level_of_deliq', 'num_deliq_6_12mts', 'num_times_60p_dpd',
       'num_std_12mts', 'num_sub', 'num_sub_6mts', 'num_sub_12mts', 'num_dbt',
       'num_dbt_12mts', 'num_lss', 'recent_level_of_deliq', 'CC_enq_L12m',
       'PL_enq_L12m', 'time_since_recent_enq', 'enq_L3m', 'NETMONTHLYINCOME',
       'Time_With_Curr_Empr', 'CC_Flag', 'PL_Flag', 'pct_PL_enq_L6m_of_ever',
       'pct_CC_enq_L6m_of_ever', 'HL_Flag', 'GL_Flag', 'MARITALSTATUS',
       'EDUCATION', 'GENDER', 'last_prod_enq2', 'first_prod_enq2',
       'Approved_Flag'],
      dtype='object')

In [86]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
df["Approved_Flag"]=le.fit_transform(df[["Approved_Flag"]])

C:\Users\Dell\anaconda3\Lib\site-packages\sklearn\preprocessing\_label.py:114: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [87]:
X=df.drop("Approved_Flag",axis=1)
y=df["Approved_Flag"]

In [88]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [89]:
X_train.shape

(33651, 42)

In [90]:
X_test.shape

(8413, 42)

In [91]:
col=list(X_train.columns)

In [92]:
col.index("first_prod_enq2")


41

In [93]:
Ohe_col=["MARITALSTATUS","GENDER","last_prod_enq2","first_prod_enq2"]

In [94]:
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline

from sklearn.preprocessing import OrdinalEncoder
from sklearn.preprocessing import OneHotEncoder

from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier

from sklearn.metrics import accuracy_score,confusion_matrix,classification_report


In [95]:
trf=ColumnTransformer([
    ("ordinal",OrdinalEncoder(categories=[["SSC","12TH","GRADUATE","POST-GRADUATE"]]),[38]),
    ("onehotencoding",OneHotEncoder(drop="first",sparse_output=False),[37,39,40,41])
    
],remainder="passthrough")

In [96]:
model=RandomForestClassifier()
xgb=XGBClassifier(objective="multi:softmax", 
                  num_class=4,
                  colsample_bytree=0.9,
                  learning_rate=1,
                  max_depth=3,
                  alpha=10,
                  n_estimators=100
                 )


In [102]:
pipe=Pipeline([
    ("trf",trf),
    ("model",model)
])

In [103]:
pipe.fit(X_train,y_train)

Pipeline(steps=[('trf',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('ordinal',
                                                  OrdinalEncoder(categories=[['SSC',
                                                                              '12TH',
                                                                              'GRADUATE',
                                                                              'POST-GRADUATE']]),
                                                  [38]),
                                                 ('onehotencoding',
                                                  OneHotEncoder(drop='first',
                                                                sparse_output=False),
                                                  [37, 39, 40, 41])])),
                ('model', RandomForestClassifier())])

In [104]:
y_train1=pipe.predict(X_train)
y_pred=pipe.predict(X_test)
print("Training accuracy:",accuracy_score(y_train,y_train1))
print("Testing accuracy:",accuracy_score(y_test,y_pred))

print("Confusion metrics :\n",confusion_matrix(y_test,y_pred))
print("Report:\n",classification_report(y_test,y_pred))



Training accuracy: 0.9999702832010936
Testing accuracy: 0.7654819921549982
Confusion metrics :
 [[ 720  294    0    0]
 [ 110 4679  201   55]
 [  26  775  295  229]
 [   1  107  175  746]]
Report:
               precision    recall  f1-score   support

           0       0.84      0.71      0.77      1014
           1       0.80      0.93      0.86      5045
           2       0.44      0.22      0.30      1325
           3       0.72      0.72      0.72      1029

    accuracy                           0.77      8413
   macro avg       0.70      0.65      0.66      8413
weighted avg       0.74      0.77      0.74      8413



In [100]:
pipe1=Pipeline([
    ("trf",trf),
    ("model",xgb)
])
pipe1.fit(X_train,y_train)


Pipeline(steps=[('trf',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('ordinal',
                                                  OrdinalEncoder(categories=[['SSC',
                                                                              '12TH',
                                                                              'GRADUATE',
                                                                              'POST-GRADUATE']]),
                                                  [38]),
                                                 ('onehotencoding',
                                                  OneHotEncoder(drop='first',
                                                                sparse_output=False),
                                                  [37, 39, 40, 41])])),
                ('model',
                 XGBClassifier(alpha=10, base_score=None, booster=None,
                               callbacks=None, colsample_bylevel=None,...
                               enable_categorical=False, eval_metric=None,
                               feature_types=None, gamma=None, grow_policy=None,
                               importance_type=None,
                               interaction_constraints=None, learning_rate=1,
                               max_bin=None, max_cat_threshold=None,
                               max_cat_to_onehot=None, max_delta_step=None,
                               max_depth=3, max_leaves=None,
                               min_child_weight=None, missing=nan,
                               monotone_constraints=None, multi_strategy=None,
                               n_estimators=100, n_jobs=None, num_class=4, ...))])

In [101]:
y_train1=pipe1.predict(X_train)
y_pred=pipe1.predict(X_test)
print("Training accuracy:",accuracy_score(y_train,y_train1))
print("Testing accuracy:",accuracy_score(y_test,y_pred))

print("Confusion metrics :\n",confusion_matrix(y_test,y_pred))
print("Report:\n",classification_report(y_test,y_pred))

Training accuracy: 0.8143294404326766
Testing accuracy: 0.7795079044336146
Confusion metrics :
 [[ 785  228    0    1]
 [ 123 4625  244   53]
 [  31  683  404  207]
 [   1   77  207  744]]
Report:
               precision    recall  f1-score   support

           0       0.84      0.77      0.80      1014
           1       0.82      0.92      0.87      5045
           2       0.47      0.30      0.37      1325
           3       0.74      0.72      0.73      1029

    accuracy                           0.78      8413
   macro avg       0.72      0.68      0.69      8413
weighted avg       0.76      0.78      0.77      8413



In [112]:
import joblib
joblib.dump(pipe1, 'Credit_risk_modeling.pkl') 

['Credit_risk_modeling.pkl']

In [113]:
unseen_data=pd.read_excel("Unseen_Dataset.xlsx")

In [114]:
unseen_data.columns

Index(['pct_tl_open_L6M', 'pct_tl_closed_L6M', 'Tot_TL_closed_L12M',
       'pct_tl_closed_L12M', 'Tot_Missed_Pmnt', 'CC_TL', 'Home_TL', 'PL_TL',
       'Secured_TL', 'Unsecured_TL', 'Other_TL', 'Age_Oldest_TL',
       'Age_Newest_TL', 'time_since_recent_payment',
       'max_recent_level_of_deliq', 'num_deliq_6_12mts', 'num_times_60p_dpd',
       'num_std_12mts', 'num_sub', 'num_sub_6mts', 'num_sub_12mts', 'num_dbt',
       'num_dbt_12mts', 'num_lss', 'recent_level_of_deliq', 'CC_enq_L12m',
       'PL_enq_L12m', 'time_since_recent_enq', 'enq_L3m', 'NETMONTHLYINCOME',
       'Time_With_Curr_Empr', 'CC_Flag', 'PL_Flag', 'pct_PL_enq_L6m_of_ever',
       'pct_CC_enq_L6m_of_ever', 'HL_Flag', 'GL_Flag', 'MARITALSTATUS',
       'EDUCATION', 'GENDER', 'last_prod_enq2', 'first_prod_enq2'],
      dtype='object')

In [119]:
unseen_data.shape

(100, 42)

In [122]:
unseen_data

pct_tl_open_L6M  pct_tl_closed_L6M  Tot_TL_closed_L12M  \
0             0.000                0.0                   0   
1             0.000                0.0                   0   
2             0.125                0.0                   0   
3             0.000                0.0                   0   
4             0.000                0.0                   1   
..              ...                ...                 ...   
95            0.000                0.0                   0   
96            0.222                0.0                   2   
97            0.000                0.0                   0   
98            0.000                1.0                   1   
99            0.500                0.0                   0   

    pct_tl_closed_L12M  Tot_Missed_Pmnt  CC_TL  Home_TL  PL_TL  Secured_TL  \
0                0.000                0      0        0      4           1   
1                0.000                0      0        0      0           0   
2                0.000                1      0        0      0           2   
3                0.000                0      0        0      0           3   
4                0.167                0      0        0      0           6   
..                 ...              ...    ...      ...    ...         ...   
95               0.000                0      0        0      1           1   
96               0.222                0      0        0      0           1   
97               0.000                0      0        0      0           1   
98               1.000                0      0        0      0           1   
99               0.000                0      0        0      0           1   

    Unsecured_TL  ...  PL_Flag  pct_PL_enq_L6m_of_ever  \
0              4  ...        1                   0.000   
1              1  ...        0                   0.000   
2              6  ...        0                   0.000   
3              0  ...        0                   0.000   
4              0  ...        0                   0.429   
..           ...  ...      ...                     ...   
95             5  ...        1                   0.000   
96             8  ...        0                   0.000   
97             0  ...        0                   0.000   
98             0  ...        0                   0.000   
99             1  ...        0                   1.000   

    pct_CC_enq_L6m_of_ever  HL_Flag  GL_Flag  MARITALSTATUS      EDUCATION  \
0                      0.0        1        0        Married           12TH   
1                      0.0        0        0         Single       GRADUATE   
2                      0.0        1        0        Married            SSC   
3                      0.0        0        0        Married  POST-GRADUATE   
4                      0.0        1        0        Married           12TH   
..                     ...      ...      ...            ...            ...   
95                     0.0        0        0        Married       GRADUATE   
96                     0.0        0        0        Married           12TH   
97                     0.0        0        0        Married            SSC   
98                     0.0        0        0        Married           12TH   
99                     0.0        0        0        Married         OTHERS   

    GENDER  last_prod_enq2  first_prod_enq2  
0        M              PL               PL  
1        F    ConsumerLoan     ConsumerLoan  
2        M    ConsumerLoan           others  
3        M              AL               AL  
4        M    ConsumerLoan               PL  
..     ...             ...              ...  
95       M    ConsumerLoan           others  
96       M    ConsumerLoan           others  
97       M          others           others  
98       M          others           others  
99       M          others           others  

[100 rows x 42 columns]

In [128]:
unseen_data["EDUCATION"].unique()

array(['12TH', 'GRADUATE', 'SSC', 'POST-GRADUATE', 'UNDER GRADUATE',
       'OTHERS'], dtype=object)

In [129]:
unseen_data["EDUCATION"]=unseen_data["EDUCATION"].replace("OTHERS","SSC")
unseen_data["EDUCATION"]=unseen_data["EDUCATION"].replace("PROFESSIONAL","GRADUATE")
unseen_data["EDUCATION"]=unseen_data["EDUCATION"].replace("UNDER GRADUATE","GRADUATE")

In [130]:
unseen_data["EDUCATION"].unique()

array(['12TH', 'GRADUATE', 'SSC', 'POST-GRADUATE'], dtype=object)

In [132]:
model=joblib.load("Credit_risk_modeling.pkl")

In [134]:
prediction=model.predict(unseen_data)

In [137]:
prediction

array([1, 1, 1, 0, 1, 1, 2, 1, 1, 1, 1, 3, 1, 0, 2, 1, 1, 0, 2, 1, 0, 1,
       1, 3, 1, 2, 1, 1, 2, 0, 3, 1, 2, 1, 1, 3, 1, 3, 1, 1, 1, 2, 1, 2,
       3, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 3, 0, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 2, 1, 1, 3, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 3, 2, 0,
       1, 1, 1, 1, 1, 3, 3, 1, 1, 1, 1, 1])

In [146]:
from sklearn.preprocessing import FunctionTransformer

In [ ]:
trf=ColumnTransformer([
    ("funtion",FunctionTransformer(func=np.log1p),[0,1,11,12,27]),
    ("ordinal",OrdinalEncoder(categories=[["SSC","12TH","GRADUATE","POST-GRADUATE"]]),[38]),
    ("onehotencoding",OneHotEncoder(drop="first",sparse_output=False),[37,39,40,41])
    
],remainder="passthrough")

In [144]:
col.index("time_since_recent_enq")

27

In [ ]:
fun=["pct_tl_open_L6M","pct_tl_closed_L6M","Age_Oldest_TL","Age_Newest_TL","time_since_recent_enq",""]

In [147]:
trf=ColumnTransformer([
    ("funtion",FunctionTransformer(func=np.log1p),[0,1,11,12,27]),
    ("ordinal",OrdinalEncoder(categories=[["SSC","12TH","GRADUATE","POST-GRADUATE"]]),[38]),
    ("onehotencoding",OneHotEncoder(drop="first",sparse_output=False),[37,39,40,41])
    
],remainder="passthrough")
model=xgb=XGBClassifier(objective="multi:softmax", 
                  num_class=4,
                  colsample_bytree=0.9,
                  learning_rate=1,
                  max_depth=3,
                  alpha=10,
                  n_estimators=100
                 )

In [148]:
pipe2=Pipeline([
    ("trf",trf),
    ("model",model)
])

In [150]:
pipe2.fit(X_train,y_train)

Pipeline(steps=[('trf',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('funtion',
                                                  FunctionTransformer(func=<ufunc 'log1p'>),
                                                  [0, 1, 11, 12, 27]),
                                                 ('ordinal',
                                                  OrdinalEncoder(categories=[['SSC',
                                                                              '12TH',
                                                                              'GRADUATE',
                                                                              'POST-GRADUATE']]),
                                                  [38]),
                                                 ('onehotencoding',
                                                  OneHotEncoder(drop='first',
                                                                sparse_output=False),
                                                  [37, 39, 40, 41])])),
                ('model',
                 XGBClassifier(alpha=10...
                               enable_categorical=False, eval_metric=None,
                               feature_types=None, gamma=None, grow_policy=None,
                               importance_type=None,
                               interaction_constraints=None, learning_rate=1,
                               max_bin=None, max_cat_threshold=None,
                               max_cat_to_onehot=None, max_delta_step=None,
                               max_depth=3, max_leaves=None,
                               min_child_weight=None, missing=nan,
                               monotone_constraints=None, multi_strategy=None,
                               n_estimators=100, n_jobs=None, num_class=4, ...))])

In [151]:
y_train1=pipe2.predict(X_train)
y_pred=pipe2.predict(X_test)
print("Training accuracy:",accuracy_score(y_train,y_train1))
print("Testing accuracy:",accuracy_score(y_test,y_pred))

print("Confusion metrics :\n",confusion_matrix(y_test,y_pred))
print("Report:\n",classification_report(y_test,y_pred))

Training accuracy: 0.8144780244272087
Testing accuracy: 0.7784381314632117
Confusion metrics :
 [[ 783  231    0    0]
 [ 117 4630  242   56]
 [  31  689  391  214]
 [   1   70  213  745]]
Report:
               precision    recall  f1-score   support

           0       0.84      0.77      0.80      1014
           1       0.82      0.92      0.87      5045
           2       0.46      0.30      0.36      1325
           3       0.73      0.72      0.73      1029

    accuracy                           0.78      8413
   macro avg       0.72      0.68      0.69      8413
weighted avg       0.76      0.78      0.76      8413

